### ISSUE TITLE
frozen strings from in_monitor_agent cause RuntimeError

### ISSUE THREAD

**Issue by scottbuettner** [repeatedly/fluent-plugin-record-modifier#25]
It appears that the in_monitor_agent plugin uses frozen strings (for performance?). The filter_record_modifier plugin will attempt (in cases of broad wildcards, which I would like to use) to convert these keys, when the char_encoding parameter is set. This causes a runtime error.

I'd like to be able to set every event coming through my aggregators to be UTF-8. Is it possible to add a check for frozen strings, and duplicate them to be no longer frozen?

**Comment by scottbuettner** [comment]
There is an issue with gem version 0.6.1, FixNum types cannot be dup'd:

```2017-12-18 07:51:13 -0700 [error]: forward error error=#<TypeError: can't dup Fixnum> error_class=TypeError
  2017-12-18 07:51:13 -0700 [error]: suppressed same stacktrace
2017-12-18 07:51:32 -0700 [warn]: emit transaction failed: error_class=TypeError error="can't dup Fixnum" tag="denver.non
prod.app.uel.forwarder.fluentd.flowcount"
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-record-modifier-0.6.1/l
ib/fluent/plugin/filter_record_modifier.rb:121:in `dup'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-record-modifier-0.6.1/l
ib/fluent/plugin/filter_record_modifier.rb:121:in `block in set_encoding'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-record-modifier-0.6.1/l
ib/fluent/plugin/filter_record_modifier.rb:119:in `each_pair'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-record-modifier-0.6.1/l
ib/fluent/plugin/filter_record_modifier.rb:119:in `set_encoding'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-record-modifier-0.6.1/l
ib/fluent/plugin/filter_record_modifier.rb:107:in `block in filter_stream'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/event.rb:1
49:in `feed_each'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/event.rb:1
49:in `each'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-record-modifier-0.6.1/l
ib/fluent/plugin/filter_record_modifier.rb:90:in `filter_stream'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/event_rout
er.rb:152:in `block in emit'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/event_rout
er.rb:151:in `each'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/event_rout
er.rb:151:in `emit'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/event_router.rb:90:in `emit_stream'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/plugin/in_forward.rb:178:in `on_message'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/plugin/in_forward.rb:338:in `call'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/plugin/in_forward.rb:338:in `block in on_read_msgpack'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/plugin/in_forward.rb:337:in `feed_each'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/plugin/in_forward.rb:337:in `on_read_msgpack'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.6/lib/cool.io/io.rb:123:in `on_readable'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.6/lib/cool.io/io.rb:186:in `on_readable'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.6/lib/cool.io/loop.rb:88:in `run_once'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.6/lib/cool.io/loop.rb:88:in `run'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/plugin/in_forward.rb:120:in `run'
```

**Comment by scottbuettner** [comment]
@repeatedly please reopen this issue, see above stack traces. Thank you.
