### ISSUE TITLE
Fluentd crashes when plugin initialized on fluentd-0.12.42 (using v0.12-debian-onbuild docker image)

### ISSUE THREAD

**Issue by dannyk81** [repeatedly/fluent-plugin-record-modifier#27]
Hi,

I'm using fluent/fluentd:v0.12-debian-onbuild to build a custom image with extra plugins, for some reason this plugin fails to initialize when building with latest fluentd-v0.12.42

```
2017-12-16 19:00:10 +0000 [info]: reading config file path="/fluentd/etc/fluentd.conf"
2017-12-16 19:00:10 +0000 [warn]: '@' is the system reserved prefix. It works in the nested configuration for now but it will be rejected: @timestamp
2017-12-16 19:00:10 +0000 [warn]: '@' is the system reserved prefix. It works in the nested configuration for now but it will be rejected: @timestamp
2017-12-16 19:00:10 +0000 [warn]: '@' is the system reserved prefix. It works in the nested configuration for now but it will be rejected: @timestamp
2017-12-16 19:00:10 +0000 [warn]: '@' is the system reserved prefix. It works in the nested configuration for now but it will be rejected: @timestamp
2017-12-16 19:00:10 +0000 [warn]: '@' is the system reserved prefix. It works in the nested configuration for now but it will be rejected: @timestamp
2017-12-16 19:00:10 +0000 [warn]: '@' is the system reserved prefix. It works in the nested configuration for now but it will be rejected: @timestamp
2017-12-16 19:00:10 +0000 [info]: starting fluentd-0.12.42
2017-12-16 19:00:10 +0000 [info]: gem 'fluent-plugin-add-uuid' version '0.1'
2017-12-16 19:00:10 +0000 [info]: gem 'fluent-plugin-anomalydetect' version '0.1.7'
2017-12-16 19:00:10 +0000 [info]: gem 'fluent-plugin-detect-exceptions' version '0.0.8'
2017-12-16 19:00:10 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '1.13.0'
2017-12-16 19:00:10 +0000 [info]: gem 'fluent-plugin-forest' version '0.3.3'
2017-12-16 19:00:10 +0000 [info]: gem 'fluent-plugin-genhashvalue' version '0.04'
2017-12-16 19:00:10 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '1.0.0'
2017-12-16 19:00:10 +0000 [info]: gem 'fluent-plugin-multiprocess' version '0.2.2'
2017-12-16 19:00:10 +0000 [info]: gem 'fluent-plugin-prometheus' version '0.4.0'
2017-12-16 19:00:10 +0000 [info]: gem 'fluent-plugin-record-modifier' version '1.0.0'
2017-12-16 19:00:10 +0000 [info]: gem 'fluent-plugin-record-reformer' version '0.9.1'
2017-12-16 19:00:10 +0000 [info]: gem 'fluent-plugin-systemd' version '0.0.9'
2017-12-16 19:00:10 +0000 [info]: gem 'fluentd' version '0.12.42'
2017-12-16 19:00:10 +0000 [info]: adding match pattern="fluent.**" type="null"
2017-12-16 19:00:10 +0000 [info]: adding filter pattern="elastic.buffers" type="record_modifier"
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- fluent/plugin/filter (LoadError)
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.3.0/gems/fluent-plugin-record-modifier-1.0.0/lib/fluent/plugin/filter_record_modifier.rb:1:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.3.0/gems/fluentd-0.12.42/lib/fluent/plugin.rb:173:in `block in try_load_plugin'
        from /var/lib/gems/2.3.0/gems/fluentd-0.12.42/lib/fluent/plugin.rb:170:in `each'
        from /var/lib/gems/2.3.0/gems/fluentd-0.12.42/lib/fluent/plugin.rb:170:in `try_load_plugin'
        from /var/lib/gems/2.3.0/gems/fluentd-0.12.42/lib/fluent/plugin.rb:130:in `new_impl'
        from /var/lib/gems/2.3.0/gems/fluentd-0.12.42/lib/fluent/plugin.rb:63:in `new_filter'
        from /var/lib/gems/2.3.0/gems/fluentd-0.12.42/lib/fluent/agent.rb:143:in `add_filter'
        from /var/lib/gems/2.3.0/gems/fluentd-0.12.42/lib/fluent/agent.rb:62:in `block in configure'
        from /var/lib/gems/2.3.0/gems/fluentd-0.12.42/lib/fluent/agent.rb:57:in `each'
        from /var/lib/gems/2.3.0/gems/fluentd-0.12.42/lib/fluent/agent.rb:57:in `configure'
        from /var/lib/gems/2.3.0/gems/fluentd-0.12.42/lib/fluent/root_agent.rb:86:in `configure'
        from /var/lib/gems/2.3.0/gems/fluentd-0.12.42/lib/fluent/engine.rb:129:in `configure'
        from /var/lib/gems/2.3.0/gems/fluentd-0.12.42/lib/fluent/engine.rb:103:in `run_configure'
        from /var/lib/gems/2.3.0/gems/fluentd-0.12.42/lib/fluent/supervisor.rb:489:in `run_configure'
        from /var/lib/gems/2.3.0/gems/fluentd-0.12.42/lib/fluent/supervisor.rb:160:in `block in start'
        from /var/lib/gems/2.3.0/gems/fluentd-0.12.42/lib/fluent/supervisor.rb:366:in `main_process'
        from /var/lib/gems/2.3.0/gems/fluentd-0.12.42/lib/fluent/supervisor.rb:339:in `block in supervise'
        from /var/lib/gems/2.3.0/gems/fluentd-0.12.42/lib/fluent/supervisor.rb:338:in `fork'
        from /var/lib/gems/2.3.0/gems/fluentd-0.12.42/lib/fluent/supervisor.rb:338:in `supervise'
        from /var/lib/gems/2.3.0/gems/fluentd-0.12.42/lib/fluent/supervisor.rb:156:in `start'
        from /var/lib/gems/2.3.0/gems/fluentd-0.12.42/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.3.0/gems/fluentd-0.12.42/bin/fluentd:8:in `<top (required)>'
        from /usr/local/bin/fluentd:22:in `load'
        from /usr/local/bin/fluentd:22:in `<main>'
2017-12-16 19:00:10 +0000 [info]: process finished code=256
2017-12-16 19:00:10 +0000 [warn]: process died within 1 second. exit.
```

This is my Dockerfile:
```
FROM fluent/fluentd:v0.12-debian-onbuild

RUN ulimit -n 65536

RUN buildDeps="sudo make gcc g++ libc-dev ruby-dev curl telnet tcpdump" \
 && apt-get update \
 && apt-get install -y --no-install-recommends $buildDeps \

 && gem install \
        fluent-plugin-elasticsearch:1.13.0 \
        fluent-plugin-record-reformer \
        fluent-plugin-anomalydetect \
        fluent-plugin-systemd:0.0.9 \
        fluent-plugin-kubernetes_metadata_filter \
        fluent-plugin-detect-exceptions \
        fluent-plugin-multiprocess \
        fluent-plugin-prometheus:0.4.0 \
        fluent-plugin-record-modifier \
        fluent-plugin-forest \
        fluent-plugin-genhashvalue:0.04 \
        fluent-plugin-add-uuid \
        strptime \

 && gem sources --clear-all \
 && SUDO_FORCE_REMOVE=yes \
    apt-get purge -y --auto-remove \
                  -o APT::AutoRemove::RecommendsImportant=false \
                  $buildDeps \
 && rm -rf /var/lib/apt/lists/* \
           /home/fluent/.gem/ruby/2.3.0/cache/*.gem
```

**Comment by dannyk81** [comment]
Thanks! so for fluentd v0.12 we should use `v0.6.0` of the plugin?

**Comment by repeatedly** [comment]
Yes!

**Comment by dannyk81** [comment]
Got it, thanks :)

By the way, rubygems.org shows 0.6.0 & 0.6.1, but in github there's only
0.6.0

**Comment by repeatedly** [comment]
Ah, I forgot to push tag. Just pushed.
