### ISSUE TITLE
version 0.6.1 can't dup FixNums

### ISSUE THREAD

**Issue by scottbuettner** [repeatedly/fluent-plugin-record-modifier#29]
There is an issue with gem version 0.6.1, FixNum types cannot be dup'd. I believe these are probably coming from either monitor_agent or flowcounter, possibly both.

```2017-12-18 07:51:13 -0700 [error]: forward error error=#<TypeError: can't dup Fixnum> error_class=TypeError
  2017-12-18 07:51:13 -0700 [error]: suppressed same stacktrace
2017-12-18 07:51:32 -0700 [warn]: emit transaction failed: error_class=TypeError error="can't dup Fixnum" tag="denver.non
prod.app.uel.forwarder.fluentd.flowcount"
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-record-modifier-0.6.1/l
ib/fluent/plugin/filter_record_modifier.rb:121:in `dup'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-record-modifier-0.6.1/l
ib/fluent/plugin/filter_record_modifier.rb:121:in `block in set_encoding'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-record-modifier-0.6.1/l
ib/fluent/plugin/filter_record_modifier.rb:119:in `each_pair'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-record-modifier-0.6.1/l
ib/fluent/plugin/filter_record_modifier.rb:119:in `set_encoding'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-record-modifier-0.6.1/l
ib/fluent/plugin/filter_record_modifier.rb:107:in `block in filter_stream'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/event.rb:1
49:in `feed_each'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/event.rb:1
49:in `each'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-record-modifier-0.6.1/l
ib/fluent/plugin/filter_record_modifier.rb:90:in `filter_stream'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/event_rout
er.rb:152:in `block in emit'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/event_rout
er.rb:151:in `each'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/event_rout
er.rb:151:in `emit'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/event_router.rb:90:in `emit_stream'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/plugin/in_forward.rb:178:in `on_message'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/plugin/in_forward.rb:338:in `call'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/plugin/in_forward.rb:338:in `block in on_read_msgpack'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/plugin/in_forward.rb:337:in `feed_each'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/plugin/in_forward.rb:337:in `on_read_msgpack'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.6/lib/cool.io/io.rb:123:in `on_readable'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.6/lib/cool.io/io.rb:186:in `on_readable'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.6/lib/cool.io/loop.rb:88:in `run_once'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.6/lib/cool.io/loop.rb:88:in `run'
  2017-12-18 07:51:32 -0700 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.40/lib/fluent/plugin/in_forward.rb:120:in `run'
```

**Comment by repeatedly** [comment]
Ah, ruby 2.1 can't dup integer ;(
Will fix.
